### ISSUE TITLE
Don't separate concerns as much

### ISSUE THREAD

**Issue by wbhob** [shekohex/nest-router#2]
Right now, the package is separated into core and common for some reason. This is a bad practice, just flatten the folder structure a little.

**Comment by shekohex** [comment]
I just make this simple Stracture for the future , if for some reason we decided to add it as a core Module , but I don't think so , It will soon have a breacking changes , so it's not stable at all , as a README saying , it's under construction 😃

**Comment by wbhob** [comment]
haha 👍
